<a href="https://colab.research.google.com/github/snehasingh979/Data-science-with-AI/blob/main/Copy_of_DEEP_LEARNING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TENSORFLOW FUNDAMENTAL
TENSORFLOW IS A PYTHON LIBRARY USED TO BUILD,TRAIN AND DEPLOY MACHIEN LEARNING PYTHON

#TENSOR FLOW
TENSOR FLOW IS MULTI DIMENSIONAL ARRAY USED TO PROCESS DATA.


#TYPES OF TENSORS
1. SCALAR
2. VECTOR(1D)-[10,20,30]
3. MATRIX-[1,2],[3,4]
4. 3D TENSOR -INMAGE
5. 4D TENSOR-BATCH OF IMAGES



TENSOR FLOW WORKFLOW
COLLECT DATA->PREPROCESS DATA-> CONVERT DATA INTO TENSORS-> BUILD NEURAL NETWORK -> TRAIN MODEL-> EVALUATE MODEL->MAKE PREDICTION

#KERAS
KERAS IS A HIGH LEVEL LANGUAGE OF API OF TENDSORFLOW
USED TO BUILD AND TRAIN DEEP LEANRINNG MODEL EASILY

#KERAS WORKFLOW
IMPORT KERAS
|
#CREATE MODEL
|
#ADD LAYERS
|
#COMPILE MODEL
|
#TRAIN MODEL
|
#EVALUATE MODEL
|
#PREDICT





In [ ]:
from tensorflow import keras
from tensorflow.keras import Sequential # Corrected import
from tensorflow.keras.layers import Dense # Imported Dense layer

#create an empty neural network

model = Sequential() # Corrected initialization and variable name
print(model)

#add layers
#hidden layers
model.add(Dense(16, activation="relu", input_shape=(4,))) # Corrected layer definition

#hidden layers
model.add(Dense(8, activation="relu")) # Corrected layer definition
model.add(Dense(1)) # Corrected layer definition

<Sequential name=sequential, built=False>


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


#realtionship between tensorflow and keras
tensorflow -> keras api -> build neural network -> train model-> predict model


In [ ]:
#practical examples1: creating tensors

from numpy import matrix
#practical example
import tensorflow as tf

#scalar tensor()
scalar = tf.constant(10) # Assign a value to the scalar tensor
print("scalar", scalar )

#vector tensorflow
vector = tf.constant([10,20,30]) # Define vector as a list of values
print("vectors ", vector ) # Corrected typo from 'vectors' to 'vector'

#matrix tensor (20)
matrix = tf.constant([[10,20],[30,40]])
print("matrix", matrix)

scalar tf.Tensor(10, shape=(), dtype=int32)
vectors  tf.Tensor([10 20 30], shape=(3,), dtype=int32)
matrix tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [ ]:
from __future__ import division
#practical example 2 matrix multiplication  tensorflow

import tensorflow as tf
#create tensor
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])

# Addition
addition = tf.add(tensor_a, tensor_b)
print("Addition (A + B):",
      addition)

# Subtraction
Subtraction = tf.subtract(tensor_a, tensor_b)
print("Subtraction (A - B):",
      Subtraction)

# Multiplication (element-wise)
multiplication = tf.multiply(tensor_a, tensor_b)
print("Element-wise Multiplication (A * B):",
      multiplication)

# Division (element-wise)
division = tf.divide(tensor_a, tensor_b)
print("Element-wise Division (A / B):",
      division)

Addition (A + B): tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Subtraction (A - B): tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
Element-wise Multiplication (A * B): tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Element-wise Division (A / B): tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [ ]:
#practical example 2. matrix multiplication
import tensorflow as tf
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
c = tf.matmul(a, b)
result = tf.add(c, 10)
print(result)

#building neural network
building neural network is the process of creating the structure of ann by adding layers,neurons and activation functions using tensorflow and keras.
#step to build a neural netowrk

import libraries -> creating sequeantial model-> add input layer-> add hidden layers -> add ouput layers -> compile model -> train model-> make predictions

#components of neural networks

1. input layer
2. hidden layer
3. ouput layer


In [ ]:
from tensorflow import keras
from tensorflow.keras import Sequential, Input
from tensorflow.keras.layers import Dense

# CREATE NEURAL NETWORK
model = Sequential()

# Define the input shape using an Input layer
model.add(Input(shape=(4,)))

# FIRST DENSE LAYER
model.add(Dense(
    units=16,
    activation="relu"
))

# HIDDEN LAYER
model.add(Dense(
    units=8,
    activation="relu"
))

# hidden layer
model.add(Dense(
    units=4,
    activation="relu"
))

# OUTPUT LAYER
model.add(Dense(
    units=1,
    activation="sigmoid"
))


#display model summary
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 257 (1.00 KB)

 Trainable params: 257 (1.00 KB)

 Non-trainable params: 0 (0.00 B)

#model compilation in tensorflow $ keras
model compilation is the process of configuring a neural network by specifing the optimizer loss function and evaluation metrices before training

components
1. optimizer - an optimizer is adjust of the neural network to minimize the loss and improve prediction accuracy
#adam.
#sgd
#rmsrop
#adgrad
#2. loss function the loss function calculates error of the neural network
#binary_crossentropy
#categorial_crossentropy
#mean_squared_error(mse)
3. metrics - metrices evaluate how well the neural network is pending or performing.


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import Input

# Create model
model = Sequential()

# Use Input layer for shape
model.add(Input(shape=(4,)))

# Add layers
model.add(Dense(16, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(4, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

# Compile model (corrected from 'models' to 'model')
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Display summary
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 257 (1.00 KB)

 Trainable params: 257 (1.00 KB)

 Non-trainable params: 0 (0.00 B)

#TRAINING AND VALIDATION IN TENSORFLOW & KERAS

1. TRAINING -  TRAINING IS THE PROCESS OF TEACHING A NEURAL NETWORK USING TRAINNG DATA SO THAT IF CAN ACCURATE PREDICTION
2. VALIDATION VALIDATION IS THE PROCESS OF CHECKING THE MODEL'S PERFORMANCE ON UNSEEN DATA DURING TRAINING.


BIOLOGICAL VS ARTIFICAL NEURONS IN ANN

BIOLOGICAL NEURON
A BIOLOGICAL IS THEBASIC FUNCTIONAL UNIT OF THE HUMAN NERVOUS SYSTEM. IT RECIEVE SIGNALS FROM OTHER NEURONS PROCESS THEM, AND SENDS SIGNALS
TO THE NEXT NEURONS .

                        DENDRITES
                        /   |   \
                       /    |    \
                      INPUT   SIGNALS
                            |
                      +-------------+
                      | CELLL BODY |
                      | (SOMA)     |
                      +-------------+
                            |
                          axon
                            |
                        output signal



                        #artifical neuron

---


an artifical neuron is the mathematical model of a biological neurons used in artifical neurons(ANNs).it recieves input value,performs calculations ,applies an activation functions and produce an ouput.




x1
  \
  x2 -----\
           \
  x3---------> (weighted sum)
            /       |     
  x4------ /      ACTIVATION FUNCTION
                    |
                    OUPUT

                        

#MAPPING BETWEEN  BIOLOGICAL AND ARTIFICAL NEURONS

BIOLOGICAL NEURONS ARTIFCIAL NEURONS
1. DENDRITIES ------>INPUTS(X)
2. SYNAPSE--------->WEIGHTS(W)
3. CELL BODY-------->WEIGHTED SUM()
4. AXON --------> OUTPUT(Y)
5. BRAIN-------> NEURON NETWORK \(ANN)



#ACTIVATION FUNCTIONS
AN ACTIVATIONS FUNCTIONS DETERMINE THE OUTPUT OF A NEURONS BY TRANSFORMING THE WEIGHTED SUM INTO A MEANINGFUL VALUE.


INPUTS (X)-> WEIGHTED SUM()-> ACTIVATION FUNCTIONS -> OUTPUT


TYPES OF ACTIVATION FUNCTIONS

1. BINAARY STEP -
THE BINARY STEP FUNCTIONS GIVES ONLY TWO OUTPUT (0,1) IT IS MAINALY USED IN PRECEPTIONS MMODELS
2. SIGMOID FUNCTIONS- IT CONVERTS ANY INPUT INTO VALUE BETWEEN 0 AND 1.
3. TANHB FUNCTIONS
THE TANH FUNCTIONS OUTPUT VALUE BETWEEEN -1 AND +1



#RELU(RECTIFIED LINEAR UNIT)
IS IS USED ACTIVATION AS THE ACTIVATION FUNCTIONS IN DEEP LEARNING

#5LEAKY RELU
LEAKY RELU IS AN IMPROVED VERSION OF RELU.INSTEAD OF RETURNING O FOR NEGATIVE Values it returns a small negative value.

#6. softmax
softmax is used for multiclass classification
it converts ouputs into probABILITIES WHOSE TOTAL IS 1



#PERCEPRON MODEL
  a perceptron moodel is the simplest artifical neural network(ann) and is the building block of deeep learning it was introduced by frank rosenblatt in 1958
  it is mainly used for binary classification where the output has only two classes

  1.  yes/no
  2.  pass/fail.
  3. spam/not spam
  4. survived/ not survived



      inputs
    x1  x2  x3
     |   |   |
     w1  w2   w3
     \    |     /
      \   |    /
      weighted sum()
          |
          +bias (b)
          |
          activation function
          |
          output(0 or 1)
      

In [ ]:
import numpy as np
hours=8
attendance=90
w1=0.6
w2=0.4
bias=-4
z=(hours*w1)+(attendance*w2)+bias
print("Weighted Sum:",z)
if z>=0:
  print("Predicition:Pass")
else:
  print("Prediction:Fail")

Weighted Sum: 36.8
Predicition:Pass


Feed forward neural network


A Feed Forward Neural Network is a neural network where information movesonly from the input layer to the output layer without any backward connections.

INPUT LAYERS

HIDDEN LAYERS

OUTPUT LAYERS

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import Input

# Create model
model = Sequential()

#input layers
model.add(Input(shape=(4,)))

# Add layers
model.add(Dense(16, activation="relu"))
model.add

#output layer
model.add(Dense(1, activation="sigmoid"))
#display model architecture


Backpropagation in Artificial Neural Nettwork(ANN)

Backpropagation is the process of sending the prediction error back  throught the neural network to update weight and  improve accurancy

WHY DO WE NEED BACKPROPAAGATION

1.make a predicition

2.calculate the error loss

3.send the error backward

4.update the weight

5.improve the next preediction

WORKFLOW

input data--> forward propagation--> prediction-->calculates loss-->backpropagation-->update weight-->repeart for next  epoach

In [ ]:
# ==========================================================
# BACKPROPAGATION EXAMPLE USING TENSORFLOW & KERAS
# ==========================================================

# Import Required Libraries
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

# ==========================================================
# STEP 1 : Load Dataset
# ==========================================================

df = pd.read_csv("/content/train.csv")

# ==========================================================
# STEP 2 : Data Preprocessing
# ==========================================================

# Select Features
X = df[["Pclass","Sex","Age","SibSp","Parch","Fare","Embarked"]]

# Target Variable
y = df["Survived"]

# Fill Missing Values
X["Age"] = X["Age"].fillna(X["Age"].mean())

# Encode Categorical Columns
X["Sex"] = X["Sex"].map({"male":0,"female":1})
X["Embarked"] = X["Embarked"].map({"S":0,"C":1,"Q":2})

X = X.fillna(0)

# Feature Scaling
sampler = StandardScaler()
X = sampler.fit_transform(X)

# ==========================================================
# STEP 3 : Split Dataset
# ==========================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

# ==========================================================
# STEP 4 : Build Neural Network
# ==========================================================

model = Sequential([
    tf.keras.Input(shape=(X_train.shape[1],)), # Explicit Input layer
    Dense(units=16, activation="relu"),
    Dense(units=8, activation="relu"),
    Dense(units=1, activation="sigmoid")
])

# ==========================================================
# STEP 5 : Compile Model
# ==========================================================

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# ==========================================================
# STEP 6 : Train Model
# ==========================================================

history = model.fit(
    X_train,
    y_train,
    validation_split=0.20,
    epochs=200,
    batch_size=32,
    verbose=1
)

# ==========================================================
# STEP 7 : Evaluate Model
# ==========================================================

loss, accuracy = model.evaluate(X_test, y_test)

print("Loss :", loss)
print("Accuracy :", accuracy)

/tmp/ipykernel_920/2105722093.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Age"] = X["Age"].fillna(X["Age"].mean())
/tmp/ipykernel_920/2105722093.py:33: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Sex"] = X["Sex"].map({"male":0,"female":1})
/tmp/ipykernel_920/2105722093.py:34: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/panda

Epoch 1/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.3972 - loss: 0.7393 - val_accuracy: 0.4406 - val_loss: 0.7274
Epoch 2/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5132 - loss: 0.6969 - val_accuracy: 0.5385 - val_loss: 0.6909
Epoch 3/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6450 - loss: 0.6657 - val_accuracy: 0.6783 - val_loss: 0.6642
Epoch 4/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7047 - loss: 0.6400 - val_accuracy: 0.6783 - val_loss: 0.6426
Epoch 5/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7223 - loss: 0.6191 - val_accuracy: 0.7063 - val_loss: 0.6213
Epoch 6/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7346 - loss: 0.5997 - val_accuracy: 0.7343 - val_loss: 0.6012
Epoch 7/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7522 - loss: 0.5798 - val_accuracy: 0.7483 - val_loss: 0.5806
Epoch 8/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7733 - loss: 0.5601 - val_accuracy: 0.7692 - 

Hyperparameter tuning

Hyperparameter tuning is the process of hinding  the optimal value of hyperparameter to improve a model's accurancy and reduce error

COMMON HYPERPARAMETER

1.learning rate

2.epochs

3.batch size

4.optimizer

5.hidden layer

6.number of neural

7.activation function

8.dropout rate



In [ ]:
# ==========================================================
# HYPERPARAMETER TUNING USING TENSORFLOW & KERAS
# ==========================================================

# Import Required Libraries
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# ==========================================================
# STEP 1 : Load Dataset
# ==========================================================

df = pd.read_csv("/content/train.csv")

# ==========================================================
# STEP 2 : Data Preprocessing
# ==========================================================

# Select Features
X = df[["Pclass","Sex","Age","SibSp","Parch","Fare","Embarked"]]

# Target Variable
y = df["Survived"]

# Fill Missing Values
X["Age"] = X["Age"].fillna(X["Age"].mean())

# Convert Categorical Columns into Numbers
X["Sex"] = X["Sex"].map({"male":0,"female":1})
X["Embarked"] = X["Embarked"].map({"S":0,"C":1,"Q":2})

# Fill Remaining Missing Values
X = X.fillna(0)

# Feature Scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)

# ==========================================================
# STEP 3 : Train-Test Split
# ==========================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

# ==========================================================
# STEP 4 : Hyperparameters
# ==========================================================

learning_rates = [0.1, 0.01, 0.001]

batch_sizes = [16, 32]

epochs_list = [20, 50]

# Variables to Store Best Result
best_accuracy = 0
best_parameters = {}

# ==========================================================
# STEP 5 : Hyperparameter Tuning
# ==========================================================

for lr in learning_rates:

    for batch in batch_sizes:

        for epochs in epochs_list:

            print("="*60)
            print("Learning Rate :", lr)
            print("Batch Size    :", batch)
            print("Epochs        :", epochs)

            # Build Model
            model = Sequential()

            model.add(Dense(
                16,
                activation="relu",
                input_shape=(X_train.shape[1],)
            ))

            model.add(Dense(
                8,
                activation="relu"
            ))

            model.add(Dense(
                1,
                activation="sigmoid"
            ))

            # Create Optimizer
            optimizer = Adam(learning_rate=lr)

            # Compile Model
            model.compile(
                optimizer=optimizer,
                loss="binary_crossentropy",
                metrics=["accuracy"]
            )

            # Train Model
            history = model.fit(
                X_train,
                y_train,
                validation_split=0.20,
                epochs=epochs,
                batch_size=batch,
                verbose=0
            )

            # Get Highest Validation Accuracy
            accuracy = max(history.history["val_accuracy"])

            print("Validation Accuracy :", accuracy)

            # Store Best Hyperparameters
            if accuracy > best_accuracy:

                best_accuracy = accuracy

                best_parameters = {

                    "Learning Rate": lr,

                    "Batch Size": batch,

                    "Epochs": epochs
                }

# ==========================================================
# STEP 6 : Display Best Hyperparameters
# ==========================================================

print("\n")
print("="*60)
print("BEST HYPERPARAMETERS")
print("="*60)

print("Best Validation Accuracy :", best_accuracy)

print(best_parameters)

/tmp/ipykernel_920/3114654195.py:33: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Age"] = X["Age"].fillna(X["Age"].mean())
/tmp/ipykernel_920/3114654195.py:36: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Sex"] = X["Sex"].map({"male":0,"female":1})
/tmp/ipykernel_920/3114654195.py:37: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/panda

Learning Rate : 0.1
Batch Size    : 16
Epochs        : 20
Validation Accuracy : 0.867132842540741
Learning Rate : 0.1
Batch Size    : 16
Epochs        : 50
Validation Accuracy : 0.8741258978843689
Learning Rate : 0.1
Batch Size    : 32
Epochs        : 20
Validation Accuracy : 0.8601398468017578
Learning Rate : 0.1
Batch Size    : 32
Epochs        : 50
Validation Accuracy : 0.867132842540741
Learning Rate : 0.01
Batch Size    : 16
Epochs        : 20
Validation Accuracy : 0.8531468510627747
Learning Rate : 0.01
Batch Size    : 16
Epochs        : 50
Validation Accuracy : 0.8601398468017578
Learning Rate : 0.01
Batch Size    : 32
Epochs        : 20
Validation Accuracy : 0.8391608595848083
Learning Rate : 0.01
Batch Size    : 32
Epochs        : 50
Validation Accuracy : 0.867132842540741
Learning Rate : 0.001
Batch Size    : 16
Epochs        : 20
Validation Accuracy : 0.8601398468017578
Learning Rate : 0.001
Batch Size    : 16
Epochs        : 50
Validation Accuracy : 0.8461538553237915
Learn

Artifial Neural Network(ANN)

An artifical neural network is a comutational model that learns relationship  between input and output by adjusting weight through training

1.face recognintion- identify people

2.gmail-spam detection

3.medical diagnosis-diesase prediction